<?php

/**
 * @file
 * Module related hooks.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\views\ViewExecutable;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Implements hook_theme().
 */
function vactory_forums_theme($existing, $type, $theme, $path) {
  return [
    'node__vactory_forum__full' => [
      'base hook' => 'node',
      'template' => 'full',
    ],
    'node__vactory_forum__card_inline' => [
      'base hook' => 'node',
      'template' => 'card-inline',
    ],
    'node__vactory_forum__smart_search' => [
      'base hook' => 'node',
      'template' => 'smart-search',
    ],
    'views_view_table__vactory_forums' => [
      'base hook' => 'views_view_table',
      'template' => 'vactory-forums-view-table',
    ],
    'views_view_field__last_comment_name' => [
      'base hook' => 'views_view_field',
      'template' => 'vactory-forums-last-comment-author',
    ],
    'views_view_field__field_vactory_forum_status' => [
      'base hook' => 'views_view_field',
      'template' => 'vactory-forums-status',
    ],
    'views_view_field__field_vactory_forum_room' => [
      'base hook' => 'views_view_field',
      'template' => 'vactory-forums-room',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function vactory_forums_node_presave(EntityInterface $entity) {
  if ($entity->bundle() == 'vactory_forum') {
    $comment = $entity->get('comment')->getValue();
    if ($entity->get('field_vactory_forum_status')->value == "1") {
      $comment[0]['status'] = 2;
    }
    else {
      $comment[0]['status'] = 1;
    }
    $entity->set('comment', $comment);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function vactory_forums_theme_suggestions_views_view_table_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'views_view_table__' . $variables['view']->id();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function vactory_forums_theme_suggestions_views_view_field_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'views_view_field__' . $variables['field']->field;
}

/**
 * Implements hook_preprocess_hook().
 */
function vactory_forums_preprocess_node__vactory_forum__full(&$variables) {
  if (isset($variables['node'])) {
    $node = $variables['node'];
    $has_access = user_has_acces_to_forum($node);
    if (!$has_access) {
      throw new NotFoundHttpException();
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function vactory_forums_views_pre_render(ViewExecutable $view) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  $routes = [
    'view.vactory_forums.page_forum_table',
    'view.vactory_forums.page_forums_listing_card',
  ];

  if (in_array($route_name, $routes)) {
    foreach ($view->result as $key => $result) {
      $node = $result->_entity;
      $has_access = user_has_acces_to_forum($node);
      if (!$has_access) {
        unset($view->result[$key]);
      }
    }
  }
}

/**
 * Check if user has access to such forum.
 */
function user_has_acces_to_forum($node) {
  if ($node instanceof NodeInterface && $node->hasField('field_groupe_utilisateurs') && !empty($node->get('field_groupe_utilisateurs'))) {
    $tids = $node->get('field_groupe_utilisateurs')->getValue();
    $tids = array_values($tids);
    $users_groups = [];
    if (!empty($tids)) {
      foreach ($tids as $t) {
        $tid = $t['target_id'];
        // Load users.
        $users = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
          'vid' => 'users_groups',
          'tid' => $tid,
        ]);
        $users = array_values($users);
        foreach ($users as $key => $user) {
          $users_tax = $user->get('field_vactory_utilisateurs')->getValue();
          foreach ($users_tax as $u) {
            if (!in_array($u['target_id'], $users_groups)) {
              array_push($users_groups, $u['target_id']);
            }
          }
        }
      }
      $current_user = \Drupal::currentUser();
      if (!$current_user->isAnonymous() && !in_array('administrator', $current_user->getRoles())) {
        $user_id = $current_user->id();
        if (!in_array($user_id, $users_groups)) {
          return FALSE;
        }
      }
    }
  }
  return TRUE;
}
