vactory_checklist.slack_notification:
  type: config_object
  label: 'Slack notification'
  mapping:
    webhook_url:
      type: string
      label: 'Incoming Webhook URL'
    notify_levels:
      type: sequence
      label: 'Levels included in Slack notifications'
      sequence:
        type: string
        label: 'Level'
