<?php

/**
 * @file
 * Contain related hooks.
 */

define('VACTORY_JOB_ADS_CANDIDATE_VIA_EMAIL', 0);
define('VACTORY_JOB_ADS_CANDIDATE_VIA_FORM', 1);
define('VACTORY_JOB_ADS_CANDIDATE_VIA_USER_SPACE', 2);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;
use Drupal\node\NodeTypeInterface;

/**
 * Implements hook_theme().
 */
function vactory_job_ads_theme() {
  return [
    // Node > Vactory Job Ads.
    'node__vactory_job_ads__card_inline' => [
      'base hook' => 'node',
      'template' => 'card-inline',
    ],

    // Node > Full Page.
    'node__vactory_job_ads__full' => [
      'base hook' => 'node',
      'template' => 'full',
    ],

    // Node > Smart search.
    'node__vactory_job_ads__smart_search' => [
      'base hook' => 'node',
      'template' => 'smart-search',
    ],
    // Node > Mur.
    'node__vactory_job_ads__mur' => [
      'base hook' => 'node',
      'template' => 'mur',
    ],

    // View > Job Ads.
    'views_view_unformatted__vactory_job_ads__vactory_job_ads' => [
      'base hook' => 'views_view_unformatted',
      'template' => 'page-list',
    ],
    // webform--vactory-job-application
    // Webform > Job Ads.
    'webform__vactory_job_application' => [
      'base hook' => 'webform',
      'template' => 'application-form',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function vactory_job_ads_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_submission_vactory_job_application_add_form') {
    $nid = (int) \Drupal::request()->query->get('nid');
    $node = Node::load($nid);
    if ($node) {
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
          $form['actions'][$action]['#submit'][] = 'vactory_job_ads_form_submit';
        }
      }

      $form['elements']['job_ad']['#default_value'] = (!$node instanceof Node) ?: $node->label();
      $form['elements']['job_ad']['#disabled'] = FALSE;
      $form['elements']['job_ad']['#type'] = 'hidden';
    }
  }
  if ($form_id == 'node_type_edit_form') {
    $type = $form_state->getFormObject()->getEntity();
    if ($type->id() == 'vactory_job_ads') {
      $form['job_ads_candidature'] = [
        '#type' => 'details',
        '#title' => t('Candidatures Spontanées'),
        '#group' => 'additional_settings',
      ];
      $default_value = $type->getThirdPartySetting('vactory_job_ads', 'candidature_node', '') != '' ? (Node::load($type->getThirdPartySetting('vactory_job_ads', 'candidature_node', '')) ?? '') : '';
      $form['job_ads_candidature']['candidature_node'] = [
        '#title' => t('Node vers la page du candidature spontanées'),
        '#type' => 'entity_autocomplete',
        '#target_type' => 'node',
        '#selection_settings' => [
          'target_bundles' => ['vactory_page'],
        ],
        '#default_value' => $default_value,
      ];
      $form['#entity_builders'][] = 'vactory_job_ads_form_node_type_form_builder';
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function vactory_job_ads_preprocess_node(&$variables) {
  /** @var \Drupal\node\Entity\Node $node */
  $node = $variables['node'];
  if ($node->getType() != 'vactory_job_ads') {
    return;
  }

  // User login states.
  $user_is_logged_in = \Drupal::currentUser()->isAuthenticated();
  $user_is_anonymous = \Drupal::currentUser()->isAnonymous();

  // Module configuration.
  $config = \Drupal::config('vactory_job_ads.admin_settings');
  $candidate_mode = $config->get('vactory_job_ads_candidate_mode');

  // Get node fields.
  $recruiter_email = $node->get('field_vactory_email')->getString();
  $nid = $node->get('nid')->getValue()[0]['value'];

  // Get candidate form.
  /** @var \Drupal\webform\Entity\Webform $webform */
  $candidate_form = \Drupal::entityTypeManager()
    ->getStorage('webform')
    ->load('vactory_job_application');
  // Get the candidate url.
  /** @var \Drupal\Core\Url $candiate_form_url */
  $candidate_form_url = $candidate_form->toUrl();

  // Setup apply link based on candidate mode.
  $apply_link = FALSE;

  if ($candidate_mode == VACTORY_JOB_ADS_CANDIDATE_VIA_EMAIL && $recruiter_email) {
    $node_title = $node->get('title')->getString();
    $apply_link = 'mailto:' . $recruiter_email . '?subject=' . $node_title;
  }
  elseif ($candidate_mode == VACTORY_JOB_ADS_CANDIDATE_VIA_FORM ||
    ($candidate_mode == VACTORY_JOB_ADS_CANDIDATE_VIA_USER_SPACE && $user_is_logged_in)) {
    $apply_link = $candidate_form_url->setOption('query', [
      'nid' => $nid,
    ]);
  }
  elseif ($candidate_mode == VACTORY_JOB_ADS_CANDIDATE_VIA_USER_SPACE && $user_is_anonymous) {
    // Get the destination.
    $destination = $candidate_form_url->setOption('query', [
      'nid' => $nid,
    ])->toString();
    $apply_link = Url::fromUri('internal:/user/login', [
      'query' => [
        'destination' => $destination,
        'ja_msg' => 1,
      ],
    ]);
  }
  $variables['apply_link'] = $apply_link;
}

/**
 * Entity builder for the node type form with scheduler options.
 */
function vactory_job_ads_form_node_type_form_builder($entity_type, NodeTypeInterface $type, &$form, FormStateInterface $form_state) {
  $type->setThirdPartySetting('vactory_job_ads', 'candidature_node', $form_state->getValue('candidature_node'));
}

/**
 * Implements hook_entity_base_field_info().
 */
function vactory_job_ads_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() === 'node') {
    $fields['candidature_spontanee_url'] = BaseFieldDefinition::create('string')
      ->setComputed(TRUE)
      ->setReadOnly(TRUE)
      ->setTargetEntityTypeId($entity_type->id())
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', FALSE)
      ->setClass('Drupal\vactory_job_ads\Field\InternalCandidatureSpontaneeEntityFieldItemList')
      ->setTranslatable(FALSE)
      ->setRequired(FALSE);
  }

  return $fields;
}
