name: default
kind: pipeline
type: docker

steps:
  - name: phpcs
    image: docker/compose:1.29.2
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo $${DRONE_SOURCE_BRANCH}
      - echo $${DRONE_TARGET_BRANCH}
      - docker build --no-cache -f ./Dockerfile --build-arg SOURCE_BRANCH_ID=$${DRONE_SOURCE_BRANCH} --build-arg TARGET_BRANCH_ID=$${DRONE_TARGET_BRANCH} -t vactory_starter_kit/build .
  - name: code-analysis
    image: kytay/sonar-node-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      use_node_version: 20.11.1
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
