name: default
kind: pipeline
type: docker

clone:
  disable: true

workspace:
  path: /opt-cache

steps:
  - name: setup
    image: vactory/vactory-ci:latest
    pull: always
    environment:
      BITBUCKET_AUTHTOKEN:
        from_secret: BITBUCKET_AUTHTOKEN
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SLACK_TOKEN:
        from_secret: SLACK_TOKEN
      PHP_VERSION: 8.3
      COMPOSER_VERSION: 2.7.1
      DRUSH_VERSION: 8.4.1
