sonar.projectKey=vactory_starter_kit
com.sun.net.ssl.checkRevocation=false
java.net.useSystemProxies=true
sonar.sources=./
sonar.exclusions=documentation,.github,config,modules/**/tests,modules/**/modules/**/tests,**/*Test.php
sonar.cpd.exclusions=modules/**/tests,modules/**/modules/**/tests,**/*Test.php
sonar.qualitygate.wait=true
