sonar.projectKey=vactory_starter_kit
com.sun.net.ssl.checkRevocation=false
java.net.useSystemProxies=true
sonar.sources=./
sonar.exclusions=documentation,.github,config,modules/**/tests,modules/**/modules/**/tests,**/*Test.php,**/*.min.js,**/*.wasm,**/tailwindcss-iso.js,**/react*.js,**/babel*.js,modules/vactory_dynamic_block/js/*.min.js,modules/vactory_dynamic_block/js/react*.js,modules/vactory_dynamic_block/js/babel*.js,modules/vactory_dynamic_block/js/tailwindcss*.js,modules/vactory_dynamic_block/js/*.wasm
sonar.cpd.exclusions=modules/**/tests,modules/**/modules/**/tests,**/*Test.php
sonar.qualitygate.wait=true

# Ignore php:S100 rule (Method names should comply with naming convention)
# Ignore php:S1192 rule (String literals should not be duplicated)
sonar.issue.ignore.multicriteria=e1,e2

# S100
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*

# S1192
sonar.issue.ignore.multicriteria.e2.ruleKey=php:S1192
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*