<?php

/**
 * @file
 * Primary hooks.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function vactory_anchor_theme($existing, $type, $theme, $path) {
  return [
    'block_anchor'          => [
      'template'  => 'block-anchor',
      'variables' => [
        'menu_links'   => [],
        'custom_block' => NULL,
      ],
    ],
    'block_anchor_dropdown' => [
      'template'  => 'block-anchor-dropdown',
      'variables' => [
        'menu_links' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function vactory_anchor_preprocess_paragraph(&$variables) {
  // @todo: need code cleaning.
  /* @var \Drupal\paragraphs\Entity\Paragraph $p */
  $p = $variables['paragraph'];
  if ($p->hasField('field_vactory_flag_2') && $p->get('field_vactory_flag_2')->value == 1) {
    $variables['attributes']['class'] = ['paragraph-anchor'];
  }
  if ($p->hasField('field_vactory_block') && $p->field_vactory_block) {
    if ($p->field_vactory_block->plugin_id == "anchor_block") {
      $variables['attributes']['class'] = ['vp_anchor'];
    }
  }
}

/**
 * Prepares variables for Anchor templates.
 *
 * Default template: block-anchor-dropdown.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - html_attributes: An attribute holding the page language & direction.
 */
function template_preprocess_block_anchor_dropdown(array &$variables) {
  $variables['html_attributes'] = new Attribute();

  // <html> element attributes.
  $language_interface = \Drupal::languageManager()->getCurrentLanguage();
  $variables['html_attributes']['lang'] = $language_interface->getId();
  $variables['html_attributes']['dir'] = $language_interface->getDirection();
}
