<?php

/**
 * @file
 * Module related hooks.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function vactory_page_import_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() === 'paragraph') {
    $fields['paragraph_key'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Paragraph Key'))
      ->setRevisionable(TRUE)
      ->setTranslatable(FALSE)
      ->setDisplayConfigurable('form', FALSE);
  }

  return $fields;
}
