<?php

/**
 * @file
 * Primary hooks for vactory mailchimp.
 */

/**
 * Implements hook_theme().
 */
function vactory_mailchimp_theme($existing, $type, $theme, $path) {
  return [
    // Form.
    'form__mailchimp_signup_subscribe_block_vactory_mailchimp_newsletter_form' => [
      'base hook' => 'form',
      'template'  => 'form--mailchimp-newsletter',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vactory_mailchimp_form_mailchimp_signup_subscribe_block_vactory_mailchimp_newsletter_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $mailchimpSignup = mailchimp_signup_load("vactory_mailchimp_newsletter");
  $form['form_title'] = ['#markup' => $mailchimpSignup->title];
}
