<?php

/**
 * @file
 * Primary module hooks for Vactory webform anonymize module.
 */

use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\vactory_webform_anonymize\AnonymizedWebformSubmissionListBuilder;
use Drupal\webform\Entity\Webform;
use Drupal\webform\WebformInterface;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

/**
 * Implements hook_entity_type_alter().
 */
function vactory_webform_anonymize_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['webform_submission'])) {
    $entity_types['webform_submission']->setHandlerClass(
      'list_builder',
      AnonymizedWebformSubmissionListBuilder::class
    );
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function vactory_webform_anonymize_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() !== 'webform_submission') {
    return;
  }

  $webform = $entity->getWebform();
  // Check if anonymization is enabled and should be applied.
  if (!\Drupal::service('vactory_webform_anonymize.helper')
    ->shouldAnonymize($webform)) {
    return;
  }

  // Get anonymization settings.
  $settings = $webform->getThirdPartySetting('vactory_webform_anonymize', 'settings', []);

  $view_mode = $build['#view_mode'] ?? 'html';
  $data = &$build['data'];
  if ($view_mode === 'table') {
    $data = &$data['#rows'];
  }
  else {
    if ($view_mode === 'text') {
      $data = &$data['#code'];
    }
  }
  foreach ($data as $key => &$value) {
    if (in_array($key, [
      'operations',
      'sid',
      'uuid',
      'in_draft',
      'sticky',
      'locked',
      'notes',
      'serial',
      '#theme',
      '#prefix',
      '#suffix',
    ]) || strpos($key, '#') === 0) {
      continue;
    }

    $value = \Drupal::service('vactory_webform_anonymize.helper')
      ->anonymizeRecursive($value, $settings, $view_mode);
  }
}

/**
 * Implements hook_preprocess_page().
 */
function vactory_webform_anonymize_preprocess_page(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  $webform_routes = [
    'entity.webform.results_export',
    'entity.webform_submission.edit_form',
  ];
  if (in_array($route_name, $webform_routes)) {
    $webform = \Drupal::routeMatch()->getParameter('webform');
    if (is_string($webform)) {
      $webform = Webform::load($webform);
    }
    if ($webform instanceof WebformInterface) {
      if (\Drupal::service('vactory_webform_anonymize.helper')
        ->shouldAnonymize($webform)) {
        throw new AccessDeniedHttpException();
      }
    }
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function vactory_webform_anonymize_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {
  if ($route_name === 'entity.webform.results_submissions') {
    $webform = \Drupal::routeMatch()->getParameter('webform');
    if ($webform instanceof WebformInterface) {
      if (!\Drupal::service('vactory_webform_anonymize.helper')
        ->shouldAnonymize($webform)) {
        return;
      }
      unset($data['tabs'][1]['entity.webform.results_export']);
      $cacheability->addCacheContexts([
        'user.permissions',
      ]);
      $cacheability->addCacheTags($webform->getCacheTags());
    }
  }
}

/**
 * Implements hook_entity_operation_alter().
 */
function vactory_webform_anonymize_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'webform' &&
    \Drupal::currentUser()->hasPermission('administer webform')) {
    $operations['anonymize'] = [
      'title' => t('Anonymize Settings'),
      'weight' => 50,
      'url' => Url::fromRoute('entity.webform.anonymize_settings', [
        'webform' => $entity->id(),
      ]),
    ];
  }
}
