<?php

/**
 * @file
 * Vactory OTP .module file.
 */

/**
 * Implements hook_theme().
 */
function vactory_otp_theme() {
  return [
    // Mails > Mail template.
    'vactory_otp_mail_body' => [
      'template' => 'vactory-otp-mail-body',
      'variables' => [
        'body' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function vactory_otp_mail($key, &$message, $params) {
  switch ($key) {
    case 'vactory_otp_mail_body':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      $message['options'] = $params['options'];
      break;
  }
}
