vactory_diff_config_server.config_export:
  path: '/api/vactory-diff/config/export'
  defaults:
    _controller: '\Drupal\vactory_diff_config_server\Controller\ConfigExportController::export'
  methods: [GET]
  requirements:
    _role: 'anonymous'
  options:
    _format: 'json'