<?php

/**
 * @file
 * Primary hook.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function vactory_governance_theme($existing, $type, $theme, $path) {
  return [
    // Node > card.
    'node__vactory_governance__card'        => [
      'base hook' => 'node',
      'template'  => 'card',
    ],
    // Node > card inline.
    'node__vactory_governance__card_inline' => [
      'base hook' => 'node',
      'template'  => 'card-inline',
    ],
    // Node > Masonry.
    'node__vactory_governance__masonry'     => [
      'base hook' => 'node',
      'template'  => 'masonry',
    ],
    // Node > full.
    'node__vactory_governance__full'        => [
      'base hook' => 'node',
      'template'  => 'full',
    ],
    // Node > Smart search.
    'node__vactory_governance__smart_search'        => [
      'base hook' => 'node',
      'template'  => 'smart-search',
    ],
    'governance_member_block'               => [
      "variables" => ["content" => []],
      "template"  => 'block--governance-member',
    ],
    'views_view__vactory_governance__block_slider_full' => [
      'base hook' => 'views_view',
      'template' => 'block-slider-full',
    ],
    'vactory_views_grid__vactory_governance__block_three_columns_navbar' => [
      'base hook' => 'vactory_views_grid',
      'template' => 'governance-view-grid',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function vactory_governance_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if ($hook == 'vactory_views_grid') {
    $suggestions[] = $hook . '__' . $variables['view']->storage->id();
    $suggestions[] = $hook . '__' . $variables['view']->storage->id() . '__' . $variables['view']->current_display;
  }
}

/**
 * Implements hook_form_alter().
 */
function vactory_governance_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, ['node_vactory_governance_edit_form', 'node_vactory_governance_form'])) {
    $form['field_show_on_roles']['#states'] = [
      'visible' => [
        ':input[name="field_show_in_one_row[value]"]' => ['checked' => TRUE],
      ],
    ];
  }
}
