<?php

/**
 * @file
 * Primary module hooks for vactory FAQ module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function vactory_faq_theme() {
  return [
    // Node > full.
    'node__vactory_faq__full' => [
      'base hook' => 'node',
      'template'  => 'full',
    ],
    // Node > Smart search.
    'node__vactory_faq__smart_search'        => [
      'base hook' => 'node',
      'template'  => 'smart-search',
    ],
    // Node > card.
    'node__vactory_faq__card' => [
      'base hook' => 'node',
      'template'  => 'card',
    ],
    // accordion.
    'vactory_faq_accordion' => [
      'base hook' => 'aqfield_jquery_accordion_formatter',
      'template'  => 'accordion',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vactory_faq_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['search_api_fulltext']) && isset($form['#info']['filter-search_api_fulltext']['label'])) {
    $form['search_api_fulltext']['#attributes']['placeholder'] = $form['#info']['filter-search_api_fulltext']['label'];
    unset($form['#info']['filter-search_api_fulltext']['label']);
  }
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function vactory_faq_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if ($hook == 'faqfield_jquery_accordion_formatter') {
    $suggestions[] = 'vactory_faq_accordion';
  }
}
