name: 'List of Participants'
multiple: FALSE
category: 'Calendar utilities'
enabled: TRUE
fields:
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        id: "vactory_users"
        resource: user--user
        filters:
          - fields[user--user]=mail,drupal_internal__uid,field_about_the_author,field_date_of_birth,field_first_name,field_last_name,field_telephone,name,user_picture,field_user_profession,field_country
          - fields[media--image]=name,thumbnail
          - fields[file--image]=filename,uri
          - include=user_picture
          - page[offset]=0
          - page[limit]=9
          - sort[sort-name][path]=name
          - sort[sort-name][direction]=ASC
          - filter[status][value]=1
        optional_filters:
          vactory_event: node
