<?php

/**
 * @file
 * Primary Hooks..
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function vactory_dynamic_field_brightcove_preprocess_vactory_dynamic_main(&$variables) {

  if ($variables['content']['is_dummy'] == FALSE) {
    $config = \Drupal::config('vactory_dynamic_field_brightcove.settings');
    $account_id = $config->get('account_id');
    if(isset($account_id)){
      $variables['content']['components'][0]['data_account'] = $account_id;
    }
  }
}

/**
 * Implements hook_library_info_alter().
 */
function vactory_dynamic_field_brightcove_library_info_alter(&$libraries, $extension) {
  if ($extension == 'vactory_dynamic_field_brightcove') {
    $config = \Drupal::config('vactory_dynamic_field_brightcove.settings');
    $account_id = $config->get('account_id');
    if (isset($account_id)) {
      $alt = [
        'https://players.brightcove.net/' . $account_id . '/default_default/index.min.js' => [
          'type' => 'external',
        ],
      ];
      $libraries['video_script']['js'] = $alt;
    }
  }
}
