<?php

/**
 * @file
 * Module related hooks.
 */

/**
 * Implements hook_mail().
 */
function vactory_flood_control_mail($key, &$message, $params) {
  switch ($key) {
    case 'vactory_flood_control_mail':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      $message['options'] = $params['options'];
      break;
  }

}
