<?php

/**
 * @file
 * Primary module hooks for Vactory Node Owner Override module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function vactory_core_node_presave(EntityInterface $entity) {
  $config = Drupal::config('vactory_node_owner_override.settings');
  $policy = $config->get('policy');
  $bundles = array_filter($config->get('bundles'));
  $is_node_concerned = !$policy ? in_array($entity->bundle(), $bundles) || empty($bundles) : FALSE;
  $is_node_concerned = !$is_node_concerned ? !in_array($entity->bundle(), $bundles) : $is_node_concerned;
  $is_node_concerned = $policy && empty($bundles) ? FALSE : $is_node_concerned;
  if ($is_node_concerned) {
    $entity->setOwnerId(Drupal::currentUser()->id());
  }
}

