<?php

namespace Drupal\vactory_migrate_ui\Form;


use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use League\Csv\Reader;



/**
 * Migration import form.
 */
class Import extends FormBase {


  /**
   * Returns a unique string identifying the form.
   *
   * The returned ID should be a unique string that can be a valid PHP function
   * name, since it's used in hook implementation names such as
   * hook_form_FORM_ID_alter().
   *
   * @return string
   *   The unique string identifying the form.
   */
  public function getFormId() {
    return 'vactory_migrate_ui.import';
  }

  /**
   * Form constructor.
   *
   * @param array $form
   *   An associative array containing the structure of the form.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   The current state of the form.
   *
   * @return array
   *   The form structure.
   */
  public function buildForm(array $form, FormStateInterface $form_state) {

    $url_options = ['absolute' => TRUE];
    $t_args = [
      ':settings_url' => Url::fromUri('base:/admin/structure/file-types/manage/document/edit', $url_options)
        ->toString(),
    ];
    $message = t('If you\'re having trouble uploading the csv file. Add <strong><em>text/csv</em></strong> <a target="_blank" href=":settings_url"> to the allowed <em>MIME types</em></a>.', $t_args);

    $form['#prefix'] = '';

    $form['migration'] = [
      '#type'         => 'select',
      '#title'        => $this->t('Migration'),
      '#options'      => $this->getMigrationsList(),
      '#empty_option' => $this->t("-- Choose import --"),
      '#description'  => t("Choose the import to perform."),
      '#required'     => TRUE,
    ];

    $form['csv'] = [
      '#type'              => 'managed_file',
      '#title'             => $this->t('CSV file'),
      '#name'              => 'csv',
      '#upload_location'   => 'temporary://migrate', //todo : to define
      '#upload_validators' => [
        'file_validate_extensions' => ['csv'],
      ],
      '#description'       => t("Load the csv file to import.<br>" . $message),
      '#required'          => TRUE,
    ];



    $form['type'] = [
      '#type'        => 'radios',
      '#title'       => $this->t("Type d'import"),
      '#options'     => [
        'diff' => $this->t('Diff'),
        'full' => $this->t('Full'),
      ],
      '#description' => t("<b>Diff</b> : Select this option if you want to import a differential file.<br><b>Full</b> : Choose this option if you want to completely replace the existing data.<br>"),
      '#required'    => TRUE,
    ];

    $form['submit'] = [
      '#type'        => 'submit',
      '#value'       => $this->t("Start import"),
      '#button_type' => 'primary',
    ];


    return $form;
  }




  public function validateForm(array &$form, FormStateInterface $form_state) {
//    Check if header is correct
    $migration_id = $form_state->getValue('migration');
    $csv = $form_state->getValue('csv');
    // Validation de header
    if (isset($csv)) {
      $original_path = $this->getMigrationSource($migration_id);
      $header = $this->getCSVHeader($original_path);
      if (!empty($header)) {
        $fid = (int) reset($csv);
        $new_header = $this->getCSVHeaderByFid($fid);
        $compare_headers = array_diff($header, $new_header);
        if (!empty($compare_headers)) {
          $form_state->setErrorByName('csv', $this->t('The CSV file has an incorrect header.'));
        }
      }
    }

    //todo Duplicate ID, delimiter (comparer avec le modèle) 

    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * Form submission handler.
   *
   * @param array $form
   *   An associative array containing the structure of the form.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   The current state of the form.
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $type = $form_state->getValue('type');
    $migration_id = $form_state->getValue('migration');
    $csv = $form_state->getValue('csv');

    //Get new file
    $fid = (int) reset($csv);
    $new_file = File::load($fid);
    $new_file_path = \Drupal::service('file_system')
      ->realpath($new_file->getFileUri());
    $original_file_path = $this->getMigrationSource($migration_id);

    //prepare new file
    if ($type == 'diff'){
      $this->appendCSV($new_file_path,$original_file_path);
    }
    if ($type == 'full'){
      $this->replaceCSV($new_file_path,$original_file_path);
    }

    //Lancer rollback
    $pieces = explode('.', $migration_id);
    $id = end($pieces);

    \Drupal::service('vactory_migrate.rollback')->rollback($id, TRUE);

  }

  private function getMigrationsList() {
    $migration_configs = \Drupal::configFactory()
      ->listAll('migrate_plus.migration.');
    $migrations = [];
    foreach ($migration_configs as $migration_config) {
      $config = \Drupal::configFactory()->get($migration_config);
      $migrations[$migration_config] = $config->get('label');
    }
    return $migrations;
  }


  private function getCSVHeaderByFid($fid) {
    $file = File::load($fid);
    if ($file) {
      $new_file = \Drupal::service('file_system')
        ->realpath($file->getFileUri());
      return $this->getCSVHeader($new_file);
    }
    return [];
  }


  private function getCSVHeader($path) {
    $csv = Reader::createFromPath($path, 'r');
    if ($csv) {
      $csv->setHeaderOffset(0);
      return $csv->getHeader();
    }
    return [];
  }

  private function getMigrationSource($migration_id) {
    $migration_config = \Drupal::configFactory()->get($migration_id);
    $source = $migration_config->get('source');
    return $source['path'];
  }

  private function appendCSV($source, $destination){
    $sourceHandle = fopen($source, 'r');
    $destinationHandle = fopen($destination, 'a');
    $header = fgetcsv($sourceHandle);
    fseek($destinationHandle, 0, SEEK_END);
    fwrite($destinationHandle, PHP_EOL);
    while (($data = fgetcsv($sourceHandle)) !== false) {
      fputcsv($destinationHandle, $data);
    }
    fclose($sourceHandle);
    fclose($destinationHandle);
  }

  private function replaceCSV($source, $destination){
    if (file_exists($source)) {
      unlink($destination);
      rename($source, $destination);

    }
  }


}
