name: 'Two Columns'
multiple: FALSE
category: 'Appel Offres'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'basic_html'
  collection:
    type: json_api_collection
    label: 'JSON:API'
    options:
      '#required': TRUE
      '#default_value':
        resource: node--vactory_tender
        filters:
          - fields[node--vactory_tender]=drupal_internal__nid,path,title,field_vactory_date,field_vactory_media_document,field_vactory_excerpt,field_vactory_media_file,field_vactory_reference,field_vactory_tags
          - fields[taxonomy_term--tags]=tid,name
          - fields[media--file]=name,field_media_file
          - fields[file--document]=filename,uri
          - include=field_vactory_media_document,field_vactory_media_document.field_media_file,field_vactory_media_file,field_vactory_media_file.field_media_file,field_vactory_tags
          - page[offset]=0
          - page[limit]=2
          - sort[sort-vactory-date][path]=field_vactory_date
          - sort[sort-vactory-date][direction]=DESC
          - filter[status][value]=1
          - filter[langcode][value]=[language:langcode]
  link:
    type: url_extended
    label: 'Lien'
