<?php

/**
 * @file
 * vactory_menu_breadcrumb.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vactory_menu_breadcrumb_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    // (this serves path = admin/help/vactory_menu_breadcrumb)
    case 'help.page.vactory_menu_breadcrumb':
      $output = <<<EOT
<h5>
Vactory Menu Breadcrumb: Generate breadcrumbs based on menu position/titles.
</h5>
<p>
On the module Settings page, select options regarding the apperarance of breadcrumbs,
and select menus on which to generate menu-based breadcrumbs.
This basic behaviour is similar to the Drupal 7 version,
which in Drupal 8 is extended as follows:
</p>
<ul>
  <li>
If the "Taxonomy Attachment" option is selected for a menu,
and if the current page belongs to a taxonomy that is on that menu,
it will inherit the taxonomy page's menu breadcrumbs (e.g., to provide
breadcrumbs for blog entries that aren't on menus themselves).
  </li>
  <li>
If the "Language Handling" option is selected for a menu,
the menu will not be breadcrumbed unless its defined language matches
the current content language (recommended when you use a separate menu per language).
  </li>
  <li>
When the current page cannot be breadcrumbed according to the menu selections,
it will not generate a breadcrumb at all, and another breadcrumb builder of lower
priority will be free to generate the breadcrumb.
  </li>
</ul>
<p>
When a "taxonomy attachment" is found, the breadcrumbs will reflect the menus
only and NOT the any hierarchy within the taxonomy: yet if those taxonomy terms
are posted in a hierarchical menu then they will breadcrumb in the same way.
(For menus based automatically on a taxonomy hierarchy,
with breadcrumbs reflecting the same hierarchy,
you could use the Taxonomy Menu module.)
</p>
<h5>
Implementation Notes
</h5>
<p>
If the current page exists on more than one menu,
or has more than one possible taxonomy attachment,
it uses the first box selected in the ordered list of menus.
The order in which menus are scanned can be changed by
dragging &amp; dropping the menus on that list.
</p>
<p>
Taxonomy terms are searched in the order that their entity reference fields
appear in the current page's field listing.
One way to change an unwanted taxonomy term taking precendence over the one
you want to "attach" on would be to change the order of those fields.
</p>
<p>
When the current page is displaying the breadcrumbs of its taxonomy parent,
the breadcrumb for that taxonomy is <u>always</u> a link regardless of the
"Show current page as link" option.  (This can be confusing until we remember
that this breadcrumb <u>is not</u> for the current page, and must be a link
because the current page is no anchored at all in the menu&hellip; unlike a
breacrumb that isn't taxonomy-attached.)
</p>
EOT;
      break;

    // (this serves path = admin/config/user-interface/menu_breadcrumb)
    case 'vactory_menu_breadcrumb.settings':
      $output = <<<EOT
<p>
Select the first option to enable the Vactory Menu Breadcrumb module,
which will generate a breadcrumb trail the first match
in the selected menu below: first looking for the current page on a menu
(unless avoiding that menu due to language settings),
and then seeing if the current page belongs to a taxonomy on that menu
(whose breadcrumbs it will then inherit).
</p>
<p>
If it cannot find a menu path or a taxonomy-based path for the current page,
a breadcrumb will neither be generated nor cached and another breadcrumb builder
(e.g., the default path-based breadcrumb builder)
will be free to set the breadcrumb.
</p>
<p>
For more details, see <a href="/admin/help/vactory_menu_breadcrumb">Menu Breadcrumb Help</a>.
</p>
EOT;
      break;
  }
  return $output;
}
