<?php

/**
 * @file
 * Module related hooks.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function vactory_smart_search_theme($existing, $type, $theme, $path) {
  return [
    'page__smart_search' => [
      'base hook' => 'page',
      'template'  => 'smart-search-page',
    ],
    'form__views_exposed_form__vactory_smart_search__global' => [
      'base hook' => 'form',
      'template'  => 'smart-search-exposed-form',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vactory_smart_search_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-vactory-smart-search-global') {
    if (isset($form['type']['#options'])) {
      $new_options = Drupal::service('vactory_smart_search.manager')->filterExposedFormTypesOptions($form['type']['#options']);
      $form['type']['#options'] = $new_options;
    }
    $form['#attributes']['class'][] = 'smart-search-exposed-form';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function vactory_smart_search_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node instanceof NodeInterface) {
    $variables['content_type_label'] = $node->type->entity->label();
  }
}
