<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_configuration_form_alter().
 */
function vactory_decoupled_webform_webform_element_configuration_form_alter(array &$form, FormStateInterface $form_state) {
  $element_properties = $form_state->get('element_properties');
  if ($element_properties['type'] === 'webform_wizard_page') {
    $element_properties['icon'] = $element_properties['icon'] ?? '';
    $form['form']['icon'] = [
      '#type' => 'vactory_icon_picker',
      '#title' => 'Step icon',
      '#default_value' => $element_properties['icon'],
    ];
    $form_state->set('element_properties', $element_properties);
  }
}
