<?php

/**
 * @file
 * Module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_configuration_form_alter().
 */
function vactory_decoupled_webform_webform_element_configuration_form_alter(array &$form, FormStateInterface $form_state) {
  $element_properties = $form_state->get('element_properties');
  $webform_file_types = ['webform_document_file', 'webform_image_file'];
  if (in_array($element_properties['type'], $webform_file_types)) {
    $element_properties['default_file'] = $element_properties['default_file'] ?? '';
    $form['file']['default_file'] = [
      '#type' => 'textfield',
      '#title' => t('Default file'),
      '#default_value' => $element_properties['default_file'],
      '#description' => t('Default file ID, tokens are supported'),
    ];
  }
  if ($element_properties['type'] === 'webform_wizard_page') {
    $element_properties['icon'] = $element_properties['icon'] ?? '';
    $form['form']['icon'] = [
      '#type' => 'vactory_icon_picker',
      '#title' => 'Step icon',
      '#default_value' => $element_properties['icon'],
    ];
  }
  $form_state->set('element_properties', $element_properties);
}
