<?php

/**
 * @file
 * Primary hooks for vactory_phone_auth_decoupled module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function vactory_phone_auth_decoupled_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if (($entity_type->id() === 'user') && ($bundle === 'user')) {
    if (isset($fields['field_telephone'])) {
      $fields['field_telephone']->addConstraint('UserPhoneUnique', []);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function vactory_phone_auth_decoupled_form_user_admin_settings_alter(&$form, FormStateInterface &$form_state) {
  $phone_auth = \Drupal::config('vactory_phone_auth_decoupled.settings')->get('phone_auth_enable');

  // Add "Do not require current password" field and its fieldset
  $form['vactory_phone_auth_settings'] = [
    '#type' => 'details',
    '#open' => TRUE,
    '#title' => t('Phone Authentication - Decoupled'),
    '#weight' => -2,
  ];
  $form['vactory_phone_auth_settings']['phone_auth_enable'] = [
    '#type' => 'checkbox',
    '#title' => t('Authenticate using phone number'),
    '#description' => t("Check this box to active the authentication using the user's phone number"),
    '#default_value' => $phone_auth,
  ];

  // Add submit function which saves the settings into configuration
  $form['#submit'][] = 'vactory_phone_auth_settings_form_user_admin_settings_submit';
}

/**
 * Submit - "Save the phone auth enable" field's value into configuration
 */
function vactory_phone_auth_settings_form_user_admin_settings_submit(array &$form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('vactory_phone_auth_decoupled.settings');
  $config->set('phone_auth_enable', $form_state->getValue('phone_auth_enable'));
  $config->save();
  drupal_flush_all_caches();
}
