<?php

/**
 * @file
 * Module related hooks.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\file_entity\FileEntityInterface;
use Drupal\vactory_cloudinary\Services\VactoryCloudinaryManager;
use Symfony\Component\Console\Output\ConsoleOutput;

/**
 * Implements hook_form_alter().
 */
function vactory_cloudinary_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  // Allow changing file fields stream wrapper settings.
  if ($form_id === 'field_storage_config_edit_form') {
    $form['settings']['uri_scheme']['#disabled'] = FALSE;
  }
}

function vactory_cloudinary_batch_process($fid, $operation_message, $source, &$context) {
  $entity_type_manager = Drupal::entityTypeManager();
  if ($fid && is_numeric($fid)) {
    $file = $entity_type_manager->getStorage('file')
      ->load($fid);
    if ($file) {
      $statistics = [];
      vactory_cloudinary_move_file($file, $source, $statistics);
    }
  }
}

function vactory_cloudinary_move_file(FileEntityInterface $file, $source, &$statistics = [], $console_output = NULL) {
  if ($file) {
    if (empty($statistics)) {
      $statistics['public_files_count'] = 0;
      $statistics['moved_files_count'] = 0;
      $statistics['remained_files_count'] = 0;
    }
    $public_files_count = $statistics['public_files_count'];
    $moved_files_count = $statistics['moved_files_count'];
    $remained_files_count = $statistics['remained_files_count'];

    $uri = $file->getFileUri();
    $source_schema = $source === 'cloudinary' ? 'cloudinary://' : 'public://';
    $destination_schema = $source === 'cloudinary' ? 'public://' : 'cloudinary://';
    if (strpos($uri, $source_schema) === 0 && $file->bundle() !== 'document') {
      $public_files_count++;
      $file_system = \Drupal::service('file_system');
      $stream_wrapper_manager = \Drupal::service('stream_wrapper_manager');
      $path = str_replace($source_schema, '', $uri);
      $path_pieces = explode('/', $path);
      $path_pieces = array_map(function ($piece) {
        return \Drupal::service('transliteration')->transliterate($piece);
      }, $path_pieces);
      $path = implode('/', $path_pieces);
      $path = str_replace(' ', '-', strtolower($path));
      $destination = $stream_wrapper_manager->normalizeUri($destination_schema . $path);
      $vactory_cloudinary_manager = Drupal::service('vactory_cloudinary.manager');
      $source_file_exist = $source !== 'cloudinary' ? file_exists($uri) : FALSE;
      if ($source === 'cloudinary') {
        // Migrating files back from cloudinary to Drupal case.
        $resource = $vactory_cloudinary_manager->getCloudinaryRessource($uri);
        $source_file_exist = isset($resource['secure_url']) && file_get_contents($resource['secure_url']);
      }
      if ($uri !== $destination && $source_file_exist) {
        $is_moved = $source === 'cloudinary' ? $vactory_cloudinary_manager->moveFromCloudinary($file, $destination, $path, $resource['secure_url']) : move_file_to_cloudinary($file, $destination, $vactory_cloudinary_manager);
        $to = $source === 'cloudinary' ? 'Drupal file system' : 'cloudinary';
        if ($is_moved) {
          $moved_files_count++;
          if ($console_output) {
            $console_output->writeln('<info>Processed:</info>' . $path . ' [File id: ' . $file->id() . '] has been moved to ' . $to);
          }
        }
        else {
          $remained_files_count++;
          if ($console_output) {
            $console_output->writeln('<comment>SKIPED:</comment>' . $path . ' [File id: ' . $file->id() . '] Could not move file to ' . $to);
          }
        }
      }
    }
    else {
      if ($console_output) {
        if ($file->bundle() === 'document') {
          $console_output->writeln('<comment>SKIPED: Document files are not concerned (file uri: ' . $uri . ')</comment>');
        }
        else {
          $schema = $source === 'cloudinary' ? 'cloudinary' : 'public';
          $console_output->writeln('<comment>SKIPED: The file is not a ' . $schema . ' file (file uri: ' . $uri . ')</comment>');
        }
      }
    }
    $statistics['public_files_count'] = $public_files_count;
    $statistics['moved_files_count'] = $moved_files_count;
    $statistics['remained_files_count'] = $remained_files_count;
  }
  else {
    if ($console_output) {
      $console_output->writeln('<comment>SKIPED: No file with ID has been founded</comment>');
    }
  }
}

/**
 * Implements batch finished callback.
 */
function vactory_cloudinary_move_file_finished($success, $results, $operations) {
  $console_output = new ConsoleOutput();
  if ($success) {
    $console_output->writeln('<info>Moving public files batch operations end.</info>');
  }
  else {
    $console_output->writeln('<error>Finished with an error.</error>');
  }
}

/**
 * Create folder function.
 */
function move_file_to_cloudinary(FileEntityInterface $file, $destination, VactoryCloudinaryManager $vactory_cloudinary_manager) {
  $vactory_cloudinary_manager->moveToCloudinary($file, $destination, 'image');
  return TRUE;
}

/**
 * Implements hook_entity_type_alter().
 */
function vactory_cloudinary_entity_type_alter(array &$entity_types){
  if (isset($entity_types['file'])) {
    $entity_types['file']->setFormClass('edit', 'Drupal\vactory_cloudinary\Form\FileEditForm');
  }
}

